<template>
	<section v-if="dataArticle != null && dataArticle.title" id="profile" class="pt-24 pb-16 lg:pb-0 max-xs:min-h-screen">
		<div class="container">
			<div class="flex flex-wrap">
				<div class="w-full px-4 pt-4 pb-0 text-center">
					<h4 class="mb-3 lan-section-title" v-html="dataArticle.title"></h4>
				</div>

				<div
					class="w-full px-4 py-0 mb-0 lg:w-1/2"
					v-if="dataArticle.url && dataArticle.url.image && dataArticle.url.image.length > 0"
				>
					<div class="relative mt-10 lg:mt-9 lg:right-0">
						<img :src="dataArticle.url.image[0]" alt="Generated by https://www.fotor.com" class="w-full mx-auto" />
					</div>
				</div>

				<MarkdownComponent v-if="dataReadme" :sourceMarkdown="dataReadme"></MarkdownComponent>
			</div>
		</div>
	</section>
</template>

<script setup>
import { inject, ref, onMounted } from "vue";
import { useRoute } from "vue-router";
import markdownit from "markdown-it";
import MarkdownComponent from "../components/MarkdownComponent.vue";
import tools from "../helper/tools";

const { dataUser } = inject("dataUser");
const dataArticle = ref({});
const dataReadme = ref("");
const mdit = markdownit({
	typographer: true,
	linkify: true,
});

async function setup() {
	const route = useRoute();

	if (dataUser.value == null || typeof dataUser.value.blog == "undefined" || dataUser.value.blog == null) {
		dataUser.value = await tools.getDataUser();
	}

	for (let article of dataUser.value.blog.articles) {
		if ("" + article.id == "" + route.params.id) {
			dataArticle.value = article;
			break;
		}
	}

	const readmeUrl = ("" + dataArticle.value.url.github).replace("github.com", "raw.githubusercontent.com") + "/main/README.md";
	// console.log(readmeUrl);
	const res = await fetch(readmeUrl);
	const resText = await res.text();
	dataReadme.value = mdit.render(resText);
	// console.log(dataReadme.value);
}

onMounted(setup);
</script>
