<template>
	<section v-if="dataArticle != null && dataArticle.title" id="profile" class="pt-24 max-xs:min-h-screen">
		<div class="container max-w-5xl">
			<div class="flex flex-wrap mb-16">
				<div class="flex flex-row flex-wrap w-full px-4 pt-4 pb-0">
					<!-- <RouterLink to="/" class="ml-0 mr-1 text-sm font-bold capitalize lan-nav-link text-primary">
						Home
					</RouterLink>
					<span class="ml-0 mr-1 text-sm font-bold capitalize lan-nav-link">/</span> -->
					<RouterLink v-if="$route.meta.url?.journey" :to="$route.meta.url.journey"
						class="ml-0 mr-1 text-sm font-bold capitalize lan-nav-link text-primary">
						Back
					</RouterLink>
					<span class="ml-0 mr-1 text-sm font-bold capitalize lan-nav-link">/</span>
					<span class="ml-0 mr-1 text-sm font-bold capitalize lan-nav-link" v-html="dataArticle.title"></span>
				</div>
				<div class="w-full px-4 pt-4 pb-0 text-center">
					<h2 class="mb-3 text-2xl lan-section-title" v-html="dataArticle.title"></h2>
				</div>

				<div class="w-full px-4 py-0 mb-0 lg:w-1/2"
					v-if="dataArticle.url && dataArticle.url.image && dataArticle.url.image.length > 0">
					<div class="relative mt-10 lg:mt-9 lg:right-0">
						<img :src="dataArticle.url.image[0]" alt="Generated by https://www.fotor.com"
							class="w-full mx-auto" />
					</div>
				</div>

				<div class="w-full px-4 pt-6 mb-0" v-if="dataArticle.description">
					<p class="text-sm text-secondary" v-html="dataArticle.description"></p>
				</div>

				<template v-if="dataReadme">
					<MarkdownComponent v-if="dataReadme" :sourceMarkdown="dataReadme" class="p-4"></MarkdownComponent>
				</template>
				<template v-else>
					<LoadingComponent></LoadingComponent>
				</template>

				<div v-if="dataArticle.source && dataArticle.source.url && dataArticle.source.type == 'github'"
					class="w-full px-4 text-right">
					<a :href="dataArticle.source.url" target="_blank" class="text-sm lan-link-primary">
						View on GitHub<span class="inline-block h-[11px] ml-1 aspect-square">
							<TechnologyIcon techName="github"></TechnologyIcon>
						</span>
					</a>
				</div>
				<h4 class="px-4 my-4">Related topics</h4>
				<div v-if="dataArticle.topics && dataArticle.topics.length > 0"
					class="flex flex-wrap w-full gap-4 px-4 text-left">
					<template v-for="(topic, index) of dataArticle.topics" :key="index">
						<a v-if="$route.meta.url?.journey" :href="$route.meta.url?.journey + '/' + topic"
							class="text-sm lan-link-primary">
							#{{ topic }}
						</a>
					</template>
				</div>
			</div>
		</div>
	</section>
</template>

<script async setup>
import { inject, ref, onMounted } from "vue";
import { useRoute } from "vue-router";
// import markdownit from "markdown-it";
import tools from "../helper/tools";
import TechnologyIcon from "../components/icons/Icon.vue";
import LoadingComponent from "../components/LoadingComponent.vue";
import MarkdownComponent from "../components/MarkdownComponent.vue";

const { dataUser } = inject("dataUser");
const dataArticle = ref({});
const dataReadme = ref("");
// const mdit = markdownit({
// 	typographer: true,
// 	linkify: true,
// });

async function setup() {
	const route = useRoute();
	if (dataUser.value == null || typeof dataUser.value.journey == "undefined" || dataUser.value.journey == null) {
		dataUser.value = await tools.getDataUser();
	}

	for (let article of dataUser.value.journey.articles) {
		if ("" + article.id == "" + route.params.id) {
			dataArticle.value = article;
			break;
		}
	}
	dataReadme.value = await tools.getContentReadme(dataArticle.value.source);
}

onMounted(setup);
</script>
