<template>
	<section class="pt-24 -z-10">
		<div class="container">
			<div class="flex flex-wrap lg:flex-row-reverse">
				<!-- Right / Top side -->
				<div class="flex flex-col self-center w-full px-4 lg:justify-end lg:w-1/2 lg:text-right">
					<h1 class="text-sm font-semibold sm:text-base text-secondary md:text-xl">
						Hello,<span class="font-bold text-primary">_</span>I'am
						<span class="block mt-1 text-2xl font-bold sm:text-4xl lg:5xl text-secondary">
							<a href="/" class="text-primary">{{ text }}_</a>Kurnia
						</span>
					</h1>
					<h class="py-6 text-sm font-extrabold sm:text-lg max-w-max lg:ml-auto text-dark lg:text-2xl"
						>Unity<span class="font-bold text-primary">_</span>Developer
						<div class="border-b-[2px] mt-1 border-b-quaternary"></div
					></h>
					<p class="mb-10 text-sm font-medium leading-relaxed sm:text-base text-secondary" v-html="dataUser.quote"></p>
					<!-- <RouterLink to="/contact" class="lan-button-primary">Contact</RouterLink> -->
				</div>
				<!-- Right / Top side -->

				<!-- Left / Bottom side -->
				<div class="self-end w-full px-0 xs:px-4 lg:w-1/2">
					<div class="relative mt-10 lg:mt-9 lg:right-0">
						<span
							id="splash-liquid"
							class="absolute top-0 bottom-0 w-full transition duration-700 ease-in-out delay-100 -translate-x-1/2 text-primary -z-10 left-1/2"
							:class="{
								'scale-[8]': !isPageLoaded,
								'scale-110': isPageLoaded,
							}"
						>
							<svg width="100%" height="100%" class="fill-current" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
								<path
									d="M21.5,-46.7C24.7,-35.3,22.1,-23.3,23.2,-15.4C24.2,-7.5,29,-3.7,37.6,4.9C46.1,13.6,58.5,27.3,60.9,41.2C63.3,55.1,55.7,69.2,43.9,71.3C32.1,73.3,16.1,63.2,0,63.3C-16.1,63.3,-32.2,73.5,-46.4,72.9C-60.6,72.2,-72.9,60.7,-74.6,46.7C-76.4,32.8,-67.5,16.4,-55.2,7.1C-42.9,-2.1,-27,-4.3,-25.4,-18.4C-23.7,-32.5,-36.2,-58.5,-34.4,-70.6C-32.5,-82.8,-16.3,-81.2,-3.6,-75C9.1,-68.8,18.2,-58.1,21.5,-46.7Z"
									transform="translate(100 100)"
								></path>
							</svg>
						</span>
						<img :src="dataUser.image" alt="Erlan Kurnia | Generated by https://www.fotor.com" class="z-50 w-full mx-auto" />
					</div>
				</div>
				<!-- Left / Bottom side -->
			</div>
		</div>
	</section>
</template>

<script>
import { ref, onMounted, inject } from "vue";
export default {
	name: "HeroComponent",
	setup() {
		//#region Splash liquid as user image
		const isPageLoaded = ref(false);
		onMounted(() => {
			setTimeout(() => {
				isPageLoaded.value = true;
			}, 500);
		});
		//#endregion Splash liquid as user image

		//#region Swapping animation
		// const texts = ["kurniaer.land", "Erlan_Kurnia."];
		// const texts = ["_erlanismy.name_", "My_name_is_Erlan"];
		const texts = ["nal.re", "_Erlan"];
		const text = ref(texts[0]);
		let index = 0,
			textIndex = 0;
		const animate = () => {
			text.value = texts[textIndex].slice(0, index + 1) + texts[1 - textIndex].slice(index + 1);
			index = (index + 1) % texts[0].length;
			if (index === 0) {
				textIndex = 1 - textIndex;
				setTimeout(animate, 2000);
			} else {
				setTimeout(animate, 700);
			}
		};
		onMounted(animate);
		//#endregion Swapping animation

		const { dataUser } = inject("dataUser");

		return { text, isPageLoaded, dataUser };
	},
};
</script>
