<template>
	<section class="h-screen max-h-[960px] pt-16 pb-0 sm:pt-24 -z-10 overflow-hidden">
		<div class="container h-full">
			<div class="flex flex-wrap h-full lg:flex-row-reverse">
				<!-- Right / Top side -->
				<div
					class="flex flex-col self-center justify-center w-full px-4 xs:justify-start h-1/2 lg:h-full lg:justify-center! lg:w-1/2 lg:text-right">
					<transition name="slide-left" appear>
						<h1 style="transition-delay: 0ms"
							class="text-sm font-semibold sm:text-base text-secondary dark:text-secondaryDark md:text-xl">
							Hello,<span class="font-bold text-primary dark:text-primaryDark">_</span>I'am
						</h1>
					</transition>

					<transition name="slide-left" appear>
						<span style="transition-delay: 50ms"
							class="flex justify-start mt-1 text-3xl font-bold lg:justify-end sm:text-4xl lg:5xl text-secondary dark:text-secondaryDark">
							<a v-if="$route.meta.url.about" :href="$route.meta.url.about"
								class="flex flex-row sm:mr-5 text-primary dark:text-primaryDark">
								<span v-for="(letter, index) in letters" :key="index" class="relative w-5 md:w-6">
									<transition name="slide-up">
										<span v-if="texts[0][index] == letter" v-html="texts[0][index]"
											class="absolute"></span>
										<span v-else-if="texts[1][index] == letter" v-html="texts[1][index]"
											class="absolute"></span>
									</transition>
								</span>
							</a>_Kurnia
						</span>
					</transition>

					<transition name="slide-left" appear>
						<h style="transition-delay: 150ms"
							class="py-6 text-sm font-extrabold sm:text-lg max-w-max lg:ml-auto text-dark dark:text-light lg:text-2xl">
							Unity<span class="font-bold text-primary dark:text-primaryDark">_</span>Developer
							<div class="border-b-[2px] mt-1 border-b-quaternary dark:border-b-quaternaryDark"></div>
						</h>
					</transition>

					<transition name="slide-left" appear>
						<p v-if="data && data.quote" style="transition-delay: 200ms"
							class="mb-10 text-sm font-medium leading-relaxed sm:text-base text-secondary dark:text-secondaryDark"
							v-html="data.quote"></p>
					</transition>
					<!-- <RouterLink to="/contact" class="lan-button-primary">Contact</RouterLink> -->
				</div>
				<!-- Right / Top side -->

				<!-- Left / Bottom side -->
				<div class="self-end w-full px-0 h-1/2 lg:h-full xs:px-4 lg:w-1/2">
					<div
						class="relative h-full mx-0 mt-0 origin-bottom scale-125 max-screen-sm:scale-100 sm:scale-100 lg:-ml-16 lg:-mr-24 md:flex md:flex-col md:justify-end lg:right-0">
						<span id="splash-liquid"
							class="absolute bottom-0 w-full transition duration-500 ease-in-out delay-75 -translate-x-[55%] text-primary dark:text-primaryDark -z-10 left-1/2">
							<svg width="100%" height="100%" class="fill-current slime" viewBox="0 0 200 200"
								xmlns="http://www.w3.org/2000/svg">
								<path
									d="M26.8,-51.3C32.9,-42.8,34.9,-32.1,42.2,-23.1C49.5,-14.2,62.2,-7.1,64.8,1.5C67.4,10.1,60,20.2,55.4,33.9C50.9,47.7,49.2,65.1,40.5,69.2C31.8,73.3,15.9,64.1,2.9,59.1C-10.1,54,-20.1,53.1,-32.1,50.9C-44.2,48.7,-58.1,45.2,-60.3,36.5C-62.6,27.8,-53,13.9,-49.6,1.9C-46.2,-10,-49.1,-20,-48.6,-31.6C-48.1,-43.3,-44.3,-56.7,-35.6,-63.8C-27,-70.8,-13.5,-71.6,-1.6,-68.8C10.3,-66.1,20.6,-59.8,26.8,-51.3Z"
									transform="translate(100 100)" />
							</svg>
						</span>
						<img v-if="data" :src="data.image" alt="Erlan Kurnia | Generated by https://www.fotor.com"
							class="absolute bottom-0 z-50 w-full mx-auto aspect-square" />
					</div>
				</div>
				<!-- Left / Bottom side -->
			</div>
		</div>
	</section>
</template>

<style scoped>
@keyframes slime {

	0%,
	100% {
		transform: translate(0, 0) scale(1, 1);
	}

	50% {
		transform: translate(-10px, -10px) scale(1.5, 0.5);
	}
}

@keyframes rotate {
	0% {
		transform: rotate(0deg);
	}

	100% {
		transform: rotate(360deg);
	}
}

.slime {
	border-radius: 50%;
	/* animation: slime 1s infinite ease-in-out; */
	animation: slime 0.25s ease-in-out infinite, rotate 480s linear infinite;
}
</style>

<script setup lang="ts">
import { ref, onMounted, inject } from "vue";
// import type IDataUser from "@/helper/interfaces/IDataUser";
import DataUserSymbol from "@/helper/symbols/DataUserSymbol";

//#region Splash liquid as user image
const isPageLoaded = ref(false);
onMounted(() => {
	setTimeout(() => {
		isPageLoaded.value = true;
	}, 500);
});
//#endregion Splash liquid as user image

//#region Swapping animation
// const texts = ["kurniaer.land", "Erlan_Kurnia."];
// const texts = ["_erlanismy.name_", "My_name_is_Erlan"];
const texts = ref(["earl!", "Erlan"]);
const letters = ref(texts.value[0].split(''));
const text = ref(texts.value[0]);
let index = 0;
let textIndex = 0;
const animate = () => {
	text.value = texts.value[textIndex].slice(0, index + 1) + texts.value[1 - textIndex].slice(index + 1);
	letters.value = text.value.split('');
	index = (index + 1) % texts.value[0].length;
	if (index === 0) {
		textIndex = 1 - textIndex;
		setTimeout(animate, 2000);
	} else {
		setTimeout(animate, 700);
	}
};
onMounted(animate);
//#endregion Swapping animation

const data = inject(DataUserSymbol);
</script>
