<script setup lang="ts">
import { computed, inject, ref, watch } from "vue";
import CardProfileComponent from "@/components/CardProfileComponent.vue";
import DataAppSymbol from "@/helper/symbols/DataAppSymbol";
import { useScroll } from "@vueuse/core";
import EndpointSymbol from "@/helper/symbols/EndpointSymbol";
import type IUserProfile from "@/helper/interfaces/IUserProfile";
import tools from "@/helper/tools";

const { y: scrollY } = useScroll(window);
const windowHeight = computed(() => window.innerHeight);
const data = inject(DataAppSymbol);
const dataEndpoint = inject(EndpointSymbol);
const dataProfile = ref<IUserProfile | null>(null);
watch(() => dataEndpoint?.value, async (newVal) => {
	if (newVal) {
		dataProfile.value = (await tools.fetch<IUserProfile>(newVal.profile)).data ?? null;
	}
}, { immediate: true });
</script>

<template>
	<section id="profile" class="h-screen max-h-[960px] pt-16 pb-0 sm:pt-24 -z-10 overflow-hidden">
		<div class="container h-full">
			<h2 class="h-8 mx-auto -mb-8 text-center lan-section-title">PROFILE</h2>
			<div class="flex flex-wrap h-full lg:flex-row-reverse">
				<!-- Right / Top side -->
				<div :style="{ transform: `translate(0, ${scrollY / 1.5}px)`, filter: `blur(${(scrollY > (windowHeight / 2) ? (scrollY / 300) : 0)}px)`, }"
					class="flex flex-col self-center z-10 justify-center w-full px-4 h-1/2 lg:h-full lg:justify-center! lg:w-1/2 lg:text-right">
					<CardProfileComponent></CardProfileComponent>
					<!-- <RouterLink to="/#contact" class="mt-4 text-center w-[180px] lan-button-secondary">Get in touch
					</RouterLink> -->
				</div>
				<!-- Right / Top side -->

				<!-- Left / Bottom side -->
				<div :style="{ transform: `translate(0, ${scrollY / 2}px)`, filter: `blur(${(scrollY > (windowHeight / 2) ? (scrollY / 300) : 0)}px)`, }"
					class="self-end w-full px-0 h-1/2 lg:h-full xs:px-4 lg:w-1/2">
					<div
						class="relative h-full mx-0 mt-0 origin-bottom scale-125 max-screen-sm:scale-100 sm:scale-100 lg:-ml-16 lg:-mr-24 md:flex md:flex-col md:justify-end lg:right-0">
						<img v-if="data" :src="tools.getCdnUrl(data.image)"
							alt="Erlan Kurnia | Generated by https://www.fotor.com"
							class="absolute bottom-0 z-50 w-full mx-auto aspect-square" />
					</div>
				</div>
				<!-- Left / Bottom side -->
			</div>
		</div>
	</section>
</template>
