<template>
	<section v-if="dataUser != null && dataUser.navbarBrand" id="profile"
		class="pt-24 pb-16 lg:pb-0 max-xs:min-h-screen">
		<div class="container">
			<div class="flex flex-wrap">
				<div class="w-full px-4 pt-4 pb-0 text-center">
					<h4 class="mb-3 lan-section-title">PROFILE</h4>
				</div>
				<div class="w-full h-auto px-4 py-0 mb-0 lg:w-1/2">
					<div class="relative mt-10 h-auto lg:mt-9 lg:right-0">
						<img :src="dataUser.image" alt="Generated by https://www.fotor.com"
							class="aspect-square max-h-[440px] mx-auto" />
					</div>
				</div>
				<div class="w-full px-4 mt-12 lg:w-1/2">
					<CardProfileComponent></CardProfileComponent>
				</div>
			</div>
		</div>
	</section>
</template>

<script>
import { inject } from "vue";
import dateTimeMixins from "../helper/mixins/dateTime";
import CardProfileComponent from "./CardProfileComponent.vue";

export default {
	mixins: [dateTimeMixins],
	name: "ProfileComponent",
	components: { CardProfileComponent },
	setup() {
		const { dataUser } = inject("dataUser");
		return {
			dataUser,
		};
	},
};
</script>
