<template>
	<!-- <section v-if="dataUser != null && dataUser.navbarBrand" id="profile"
		class="pt-16 sm:pt-24 h-screen max-h-[960px] md:h-auto">
		<div class="container h-full">
			<div class="grid h-full grid-rows-[40px,auto,auto] md:grid-rows-[auto,1fr,1fr] grid-cols-1 md:grid-cols-2">
				<div
					class="order-1 w-full h-10 col-span-1 row-span-1 px-4 pt-4 pb-0 text-center md:order-1 md:col-span-2 md:row-span-1">
					<h4 class="mb-3 lan-section-title">PROFILE</h4>
				</div>
				<div
					class="order-3 w-full h-full col-span-1 row-span-1 px-4 py-0 mb-0 md:h-auto md:order-2 md:col-span-1 md:row-span-2">
					<div class="relative h-full md:h-auto md:mt-10 lg:mt-9 lg:right-0">
						<img :src="dataUser.image" alt="Generated by https://www.fotor.com"
							class="aspect-square object-cover h-full md:max-h-[440px] w-full max-w-[440px] mx-auto" />
					</div>
				</div>
				<div
					class="order-2 w-full col-span-1 row-span-1 px-4 mt-8 lg:mt-12 md:order-3 md:col-span-1 md:row-span-2 md:col-start-2">
					<CardProfileComponent></CardProfileComponent>
				</div>
			</div>
		</div>
	</section> -->

	<section id="profile" class="h-screen max-h-[960px] pt-16 pb-0 sm:pt-24 -z-10 overflow-hidden">
		<div class="container h-full">
			<h4 class="h-8 mx-auto -mb-8 text-center lan-section-title">PROFILE</h4>
			<div class="flex flex-wrap h-full lg:flex-row-reverse">
				<!-- Right / Top side -->
				<div
					class="flex flex-col self-center z-10 justify-center w-full px-4 h-1/2 lg:h-full lg:!justify-center lg:w-1/2 lg:text-right">
					<CardProfileComponent></CardProfileComponent>
				</div>
				<!-- Right / Top side -->

				<!-- Left / Bottom side -->
				<div class="self-end w-full px-0 h-1/2 lg:h-full xs:px-4 lg:w-1/2">
					<div
						class="relative h-full mx-0 mt-0 origin-bottom scale-125 max-screen-sm:scale-100 sm:scale-100 lg:-ml-16 lg:-mr-24 md:flex md:flex-col md:justify-end lg:right-0">
						<img :src="dataUser.image" alt="Erlan Kurnia | Generated by https://www.fotor.com"
							class="absolute bottom-0 z-50 w-full mx-auto aspect-square" />
					</div>
				</div>
				<!-- Left / Bottom side -->
			</div>
		</div>
	</section>
</template>

<script>
import { inject } from "vue";
import dateTimeMixins from "../helper/mixins/dateTime";
import CardProfileComponent from "./CardProfileComponent.vue";

export default {
	mixins: [dateTimeMixins],
	name: "ProfileComponent",
	components: { CardProfileComponent },
	setup() {
		const { dataUser } = inject("dataUser");
		return {
			dataUser,
		};
	},
};
</script>
