<script setup lang="ts">
import { defineAsyncComponent } from "vue";

const props = defineProps<{ techName: string, default?: string }>()
const icons = {
	unity: ["unity", "unity3d", "unityengine"],
	acmic: ["acmic"],
	android: ["android", "androidos"],
	androidstudio: ["androidstudio", "androidstudioide"],
	apidog: ["apidog"],
	apple: ["apple", "ios", "macos"],
	arduino: ["arduino", "arduinoide"],
	azure: ["azure", "microsoftazure", "azureappservice"],
	baseus: ["baseus"],
	blazor: ["blazor"],
	cloudflare: ["cloudflare"],
	codeigniter: ["codeigniter", "ci"],
	copilot: ["copilot", "microsoftcopilot"],
	cpp: ["cpp", "c++"],
	csharp: ["csharp", "c#"],
	daisyui: ["daisyui"],
	dart: ["dart", 'dart-lang'],
	dotnet: ["dotnet", ".net"],
	efcore: ["efcore", "entityframeworkcore", "entity-framework-core"],
	espressif: ["esp32", "espressif"],
	firebase: ["firebase"],
	firefox: ["firefox", "mozilla-firefox"],
	flutter: ["flutter"],
	github: ["github"],
	githubcopilot: ["github-copilot"],
	githubactions: ["github-actions"],
	google: ["google"],
	grafana: ["grafana"],
	handbrake: ["handbrake"],
	java: ["java"],
	javascript: ["javascript", "js"],
	jetpackcompose: ["jetpackcompose", "kotlincompose"],
	json: ["json"],
	kiip: ["kiip"],
	kotlin: ["kotlin"],
	laragon: ["laragon"],
	laravel: ["laravel"],
	laravelherd: ["laravelherd", "herd"],
	logitech: ["logitech"],
	mariadb: ["mariadb"],
	maxst: ["maxst", "maxstar"],
	midtrans: ["midtrans"],
	mongodb: ["mongodb", "mongo"],
	motorola: ["motorola", "moto"],
	mysql: ["mysql"],
	nginx: ["nginx"],
	nodejs: ["nodejs", "node"],
	nuxtjs: ["nuxtjs", "nuxt", "nuxt-content"],
	onesignal: ["onesignal"],
	php: ["php"],
	podman: ["podman", "podman-desktop"],
	postgresql: ["postgresql", "pqsql", "postgres"],
	powertoys: ["powertoys", "microsoft-powertoys"],
	primevue: ["primevue"],
	prometheus: ["prometheus"],
	raspberrypi: ["raspberry", "raspberry-pi"],
	rexus: ["rexus"],
	samsung: ["samsung"],
	scalar: ["scalar", "scalardocs"],
	sony: ["sony"],
	supabase: ["supabase"],
	tableplus: ["tableplus"],
	tailwindcss: ["tailwindcss", "tailwind"],
	typescript: ["typescript", "ts"],
	vention: ["vention"],
	vuejs: ["vuejs", "vue"],
	vuforia: ["vuforia", "vuforiaengine"],
	winscp: ["winscp"],
	xamarin: ["xamarin"],
	zoom: ["zoom"],
	windows11: ["windows11", "win11"],
	visualstudio: ["visualstudio", "msvisualstudio", "vs2019", "vs2017", "vs2015"],
	vscode: ["vscode", "visualstudiocode"],
	msedge: ["msedge", "microsoftedge"],
	postman: ["postman"],
	python: ["python", "py"],
	xampp: ["xampp"],
	xendit: ["xendit"],
	zoho: ["zoho"],
	notion: ["notion"],
	swift: ["swift"],
	xcode: ["xcode"],
	lenovo: ["lenovo"],
	docker: ["docker"],
	expressjs: ["expressjs", "express.js", "express"],
	lunacy: ["lunacy"],
	iot: ["iot", "internetofthing", "internetofthings"],
	simpleaccessories: ["accessories", "watch", "smartwatch"],
	simpleapi: ["restapi", "restful", "cloudapi"],
	simpleaudio: ["audio", "sound"],
	simplebrowser: ["browser", "web-browser"],
	simplecodeeditor: ["code-editor", "editor", "file-code"],
	simpledatabase: ["database", "db", "datastore"],
	simpledebugging: ["debugging", "debug", "dev-tool", "devtool"],
	simpledockrow: ["dock-row"],
	Simplesetting: ["setting", "settings", "system"],
	simpleflashdrive: ["flashdrive", "flashdisk", "on-the-go", "portable"],
	simplekeyboard: ["keyboard"],
	simplelaptop: ["computer", "laptop"],
	simplelayout: ["architecture", "layout", "keyboard layout"],
	simplemicrochip: ["microchip", "chipset", "mcu", "microcontroller"],
	simplemisc: ["misc", "miscellaneous", "other", "others"],
	simplemonitor: ["monitor", "tv"],
	simplemouse: ["mouse"],
	simplepattern: ["pattern"],
	simplephone: ["phone", "smartphone", "daily-driver"],
	simpleruler: ["ruler", "design"],
	simpletesting: ["testing", "test"],
	simpleusb: ["usb", "docking"],
	simpleweb: ["website", "internet"],
};
const currentComponentName = (techName: string, icons: Record<string, string[]>) => {
	let name: string | null = null;
	for (const [key, value] of Object.entries(icons)) {
		for (let tag of value) {
			if (tag.toLowerCase() == techName.toLowerCase()) {
				name = key.charAt(0).toUpperCase() + key.substring(1);
			}
			if (name) break;
		}
		if (name) break;
	}
	return name ?? props.default ?? 'Simpleweb';
};
const currentComponent = defineAsyncComponent(() => import(`./svg/${currentComponentName(props.techName, icons)}.svg.vue`));
</script>

<template>
	<component :is="currentComponent"></component>
</template>
